/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-03-20 12:08:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class In_005fForm_005fok_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
  request.setCharacterEncoding("euc-kr");  
      out.write("<!--한글입력전송받을때이거반드시필요.-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".style1{border-color:blue;color:blue;}\r\n");
      out.write(".style0{color:blue;background-color:lightgrey;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table class=\"style1\" border=\"1\">\r\n");
      out.write("\t<tr><th class=\"style0\" colspan=2><br><br>회원 정보 수정 양식</th></tr><!--표제목  -->\r\n");
      out.write("\t<tr><td class=\"style0\" width= \"100\"> * 아이디</td>\r\n");
      out.write("\t\t<td width=\"500\"> ");
      out.print(request.getParameter("id") );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style0\"> * 비밀번호</td>\r\n");
      out.write("\t\t<td class=\"style1\"> ");
      out.print(request.getParameter("pwd") );
      out.write("\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style0\"> * 이 름</td>\r\n");
      out.write("\t\t<td class=\"style1\">  ");
      out.print(request.getParameter("name") );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style0\"> * 이메일</td>\r\n");
      out.write("\t\t<td class=\"style1\">  ");
      out.print(request.getParameter("email") );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style0\"> 전화번호</td>\r\n");
      out.write("\t\t<td class=\"style1\">\r\n");
      out.write("\t\t\t ");
      out.print(request.getParameter("homenumber1") );
      out.write("\r\n");
      out.write("\t\t\t-\r\n");
      out.write("\t\t\t ");
      out.print(request.getParameter("homenumber2") );
      out.write("\r\n");
      out.write("\t\t\t-\r\n");
      out.write("\t\t\t ");
      out.print(request.getParameter("homenumber3") );
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style0\"> * 핸드폰번호</td>\r\n");
      out.write("\t\t<td class=\"style1\">\r\n");
      out.write("\t\t<SELECT >\r\n");
      out.write("\t\t<OPTION VALUE=\"010\">010</OPTION>\r\n");
      out.write("\t\t<OPTION VALUE=\"011\">011</OPTION>\r\n");
      out.write("\t\t<OPTION VALUE=\"012\">012</OPTION>\r\n");
      out.write("\t\t</SELECT>\r\n");
      out.write("\t\t-\r\n");
      out.write("\t\t<input type=\"text\" size=6>\r\n");
      out.write("\t\t-\r\n");
      out.write("\t\t<input type=\"text\" size=6>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style0\"> 주민번호</td>\r\n");
      out.write("\t\t<td class=\"style1\"> \r\n");
      out.write("\t\t\t ");
      out.print(request.getParameter("ssn1") );
      out.write("\r\n");
      out.write("\t\t\t -\r\n");
      out.write("\t\t\t ");
      out.print(request.getParameter("ssn2") );
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style0\"> 우편번호</td>\r\n");
      out.write("\t\t<td class=\"style1\">\r\n");
      out.write("\t\t\t ");
      out.print(request.getParameter("pn1") );
      out.write("\r\n");
      out.write("\t\t\t -\r\n");
      out.write("\t\t\t ");
      out.print(request.getParameter("pn2") );
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style0\"> 주소</td>\r\n");
      out.write("\t\t<td class=\"style1\">\r\n");
      out.write("\t\t  ");
      out.print(request.getParameter("ad") );
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style0\"> 나머지주소</td>\r\n");
      out.write("\t\t<td class=\"style1\"> \r\n");
      out.write("\t\t  ");
      out.print(request.getParameter("remainderad") );
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style0\"> 생년월일</td>\r\n");
      out.write("\t\t<td>  ");
      out.print(request.getParameter("year") );
      out.write("년&nbsp;\r\n");
      out.write("\t\t\t  ");
      out.print(request.getParameter("month") );
      out.write("월&nbsp;\r\n");
      out.write("\t\t\t  ");
      out.print(request.getParameter("day") );
      out.write("일&nbsp;\r\n");
      out.write("\t\t\t  ");
      out.print(request.getParameter("age") );
      out.write("살&nbsp;\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style1\"> 성별</td>\r\n");
      out.write("\t\t<td class=\"style1\"> ");
      out.print(request.getParameter("gender") );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style1\"> 취미</td>\r\n");
      out.write("\t\t<td class=\"style1\">\r\n");
      out.write("\t\t\t");
      out.print(request.getParameter("hobby") );
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style1\"> 직업</td>\r\n");
      out.write("\t\t<td > \r\n");
      out.write("\t\t");
      out.print(request.getParameter("job") );
      out.write("\r\n");
      out.write("\t    </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style1\"> 메일수신여부</td>\r\n");
      out.write("\t\t<td class=\"style1\">");
      out.print(request.getParameter("emailcheck") );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td class=\"style1\"> 자기소개</td>\r\n");
      out.write("\t\t<td class=\"style1\"> \r\n");
      out.write("\t\t");
      out.print(request.getParameter("intro") );
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"style0\" colspan=\"2\"><br><br></td>\r\n");
      out.write("\t</tr>\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
